INSERT INTO "role" VALUES(1, 'ROLE_USER') ON CONFLICT DO NOTHING;
INSERT INTO "role" VALUES(2, 'ROLE_ADMIN') ON CONFLICT DO NOTHING;
INSERT INTO "role" VALUES(3, 'ROLE_SYSADMIN') ON CONFLICT DO NOTHING;
